<a href="https://colab.research.google.com/github/Harikaharu/DataScience/blob/main/NLP%20/%20BOW%20/%20BOW.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import pandas as pd
import numpy as np

In [13]:
df=pd.read_csv('/content/spam1.csv')
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [15]:
df['spam']=df['Category'].apply(lambda x:1 if x=='spam' else 0)

In [16]:
df.shape

(5572, 3)

In [17]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [18]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.2)

In [19]:
X_train.shape

(4457,)

In [20]:
X_test.shape

(1115,)

In [23]:
X_train[:4]

2083                                    I'm done oredi...
4076    God picked up a flower and dippeditinaDEW, lov...
3061             K..k...from tomorrow onwards started ah?
3383    Well, I meant as opposed to my drunken night o...
Name: Message, dtype: object

In [24]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()

X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 59576 stored elements and shape (4457, 7773)>

In [25]:
X_train_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0])

In [27]:
v.get_feature_names_out()[1771]

'cheat'

In [28]:
v.vocabulary_

{'done': 2426,
 'oredi': 5002,
 'god': 3196,
 'picked': 5221,
 'up': 7206,
 'flower': 2934,
 'and': 977,
 'dippeditinadew': 2352,
 'lovingly': 4267,
 'touched': 7014,
 'itwhichturnedinto': 3804,
 'the': 6832,
 'he': 3396,
 'gifted': 3162,
 'tomeandsaid': 6972,
 'this': 6870,
 'friend': 3031,
 'is': 3782,
 '4u': 536,
 'from': 3047,
 'tomorrow': 6975,
 'onwards': 4966,
 'started': 6468,
 'ah': 888,
 'well': 7482,
 'meant': 4432,
 'as': 1098,
 'opposed': 4982,
 'to': 6949,
 'my': 4680,
 'drunken': 2492,
 'night': 4791,
 'of': 4910,
 'before': 1314,
 'sad': 5897,
 'story': 6526,
 'man': 4356,
 'last': 4058,
 'week': 7466,
 'was': 7419,
 'day': 2203,
 'wife': 7537,
 'did': 2322,
 'nt': 4860,
 'wish': 7568,
 'me': 4426,
 'parents': 5098,
 'forgot': 2976,
 'so': 6303,
 'kids': 3966,
 'went': 7485,
 'work': 7621,
 'even': 2688,
 'colleagues': 1914,
 'not': 4841,
 'entered': 2636,
 'cabin': 1612,
 'pa': 5062,
 'said': 5905,
 'happy': 3363,
 'boss': 1460,
 'felt': 2841,
 'special': 6381,
 'she':

In [29]:
X_train_np = X_train_cv.toarray()
X_train_np[0]


array([0, 0, 0, ..., 0, 0, 0])

In [30]:
np.where(X_train_np[0]!=0)


(array([2426, 5002]),)

In [31]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_cv, y_train)


MultinomialNB()

In [32]:
X_test_cv=v.transform(X_test)

In [33]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_cv)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       996
           1       0.97      0.94      0.96       119

    accuracy                           0.99      1115
   macro avg       0.98      0.97      0.98      1115
weighted avg       0.99      0.99      0.99      1115



In [34]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1])