<a href="https://colab.research.google.com/github/Harikaharu/DataScience/blob/main/Numpy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

## **Converting a List to Array**

In [ ]:
# prompt: Converting a List to Array

import numpy as np
my_list = [1, 2, 3, 4, 5]
my_array = np.array(my_list)

print(my_array)
print(type(my_array))

<class 'list'>
<class 'numpy.ndarray'>
[[1 2 3 4]]



## **Arrange function**

In [ ]:
arr=np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [ ]:
print(*arr)

1 3 5 7 9


In [ ]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Total: ",arr.size)
print('rows: ',np.size(arr,0))
print('Cols: ',np.size(arr,1))

Total:  9
rows:  3
Cols:  3


In [ ]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print((np.size(arr,0),np.size(arr,1)))
print(arr.shape)

(3, 3)
(3, 3)


In [ ]:
arr1=np.array([1,2,3,4])
arr2=np.array([5.1,6.1,7.3,8.4])
print(arr1.dtype)
print(arr2.dtype)

int64
float64


In [ ]:
arr=np.zeros(shape=(3,5),dtype=int)
print(arr)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [ ]:
arr=np.ones(shape=(3,5),dtype=int)
print(arr)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [ ]:
np.eye(4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [ ]:
np.empty(shape=(5,5))

array([[ 3.51171877e-315,  0.00000000e+000,  3.12328388e-266,
         4.75419601e-271, -5.49274122e+087],
       [ 1.44845015e-115, -6.08978645e+233, -1.39972390e-250,
         1.51543531e-246,  3.26238493e-265],
       [ 4.56588292e-304,  2.54257151e-260, -5.17302066e+178,
         5.14305820e-271,  1.42934354e-284],
       [ 4.00410618e+147,  6.82935761e-246,  5.40718455e-241,
        -4.36803804e+154,  1.68028241e-226],
       [ 4.47968280e-213,  1.23516411e-322,  0.00000000e+000,
         6.91495795e-310,  2.52961611e-321]])